person:
  name: xxy
  age: 18
  happy: false
  maps: {qisile: meiwenti,wocao: sb}
  list:
    - 苹果
    - 雪梨
    - 香蕉
  dog:
    name: xiaobai
    age: 8
server:
  port: 8082
spring:
  profiles:
    active: ssssss
---
server:
  port: 8081
spring:
  profiles: ssssss
---